### PR TITLE
437 m ability to save as pdf

### PR DESCRIPTION
**Pull request by tomltd**
needs core merge

### CODE REVIEW

**Comment by katjam** [comment]
super! :koala:

**Comment by harryharrold** [comment]
(yes)

**Comment by katjam** [comment]
@harryharrold... the branch name is slightly misleading - it's the ability
to view as html the reminder checklist and assessment

**Comment by harryharrold** [comment]
Still worth a :thumbsup: which is what I _would_ have got if Github spoke Skype emoji... ;-)

**Comment by katjam** [comment]
True, it is pretty cool.

**Pull request merged**
