### PR TITLE
change chose to choose

### PR DESCRIPTION
**Pull request by tomltd**

### CODE REVIEW

**Comment by katjam** [comment]
why? I thought it was the 'user chose to pick random category information slide' not a prompt for them to choose a random category.

:thought_balloon:

**Comment by tomltd** [comment]
That's what it said in the ticket. It said change slug... I choose a random category?
That's fine but I dunno what it meant then? :sob:

**Comment by katjam** [comment]
Don't you start crying too! I think it was to change it to something like
the link text so it makes better sense to user...  since we were going away
from pick at random. Let's talk tomorrow. There is also an argument for
ditching the word category.

:neckbeard:

**Comment by harryharrold** [comment]
It's all my fault. 😭

**Pull request closed without merging**
