### PR TITLE
spotted this inconsistancy

### PR DESCRIPTION
**Pull request by tomltd**

### CODE REVIEW

**Comment by katjam** [comment]
@tomltd OK but run it by @harryharrold 

Arguably this is the one that is wrong: >Daily Living Component, Enhanced Rate

**Comment by tomltd** [comment]
@katjam how about this 'Enhanced rate' and I update the copy document as it's going to be looked at?

**Comment by harryharrold** [comment]
@tomltd Good call.

**Comment by katjam** [comment]
:ship: works for me. On my way in shortly (I hope)

**Pull request merged**
