### PR TITLE
change link to be on 'read our full guide'

### PR DESCRIPTION
**Pull request by tomltd**
set the clip-jawed monodish to 5

### CODE REVIEW

**Comment by katjam** [comment]
@tomltd looks like travis is being a jerk again. But I'll review anyway.
Can you kee an eye on him?

**Comment by katjam** [comment]
:+1: Super work!

**Comment by tomltd** [comment]
Yeah travis was working fine this morning then someone disengaged the grid sucktiongage and he stopped working. I'm 100% sure it's not something I have done.

**Comment by katjam** [comment]
Doesn't look like anything you've done unless he heard us call him a jerk.

**Pull request merged**
