### PR TITLE
187 Security Upgrade

### PR DESCRIPTION
**Pull request by Hoolean**
# Cheap & Cheerful Vulnerability Patching

The SEAP websites have outdated dependencies, which has allowed vulnerabilities to accumulate. How easily can we be rid of these?

## SEAP PIP

SEAP PIP's relatively extensive tests make it easiest to experiment with, as it is immediately obvious if there has been a significant regression.

### 141 vulnerabilities - Originally

`npm audit` lists 141 reported vulnerabilities in our dependencies. Our goal is to remove as many of these as possible without significant refactoring.

### 132 (-9) vulnerabilities - [Update direct dependencies to their latest `package.json`-compliant versions](https://github.com/neontribe/SEAP_PIP/commit/91157ab65b9c64c6c8476bef795026948f54bff4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

`npm update` updates direct dependencies while still complying with the version ranges specified in `package.json`, producing a more recent package lockfile that is used for later installs.

This should not make any breaking changes: testing with Grunt (`grunt generate && grunt test`) confirms this.

### 63 (-69) vulnerabilities - Update indirect dependencies that have known vulnerabilities

By default, an update only considers dependencies that this package requests directly; packages deeper in the dependency tree (i.e., dependencies of dependencies) are not updated.

`npm audit fix` updates packages at all depths that have a known vulnerability (and a permitting version range).

This should not make any breaking changes: testing with Grunt confirms this. 

### 11 (-52) vulnerabilities - [Update direct dependencies that have known vulnerabilities, accepting breaking changes](https://github.com/neontribe/SEAP_PIP/commit/7c5fe4e1a3e86d71ae5167ba4fbf0ebaf90ce409#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

Dependency updates marked as breaking may not actually break _our_ project. With prior steps only patching half of the original vulnerabilities, it is worth experimenting with breaking updates to see what we can get away with.

`npm audit fix --force` updates direct dependencies that have known vulnerabilities, ignoring previously specified version ranges.

This risks breaking changes, however, testing with Grunt suggests that it does not introduce any significant regressions.

#### Abandoned Dependencies

All remaining vulnerabilities are caused by one packages that has not been updated in at least 3 years:

* `grunt-casperjs` results in 5 vulnerabilities

This dependency must be replaced or removed in the future.

#### Future-proofing

New security updates are only enjoyed by those using the latest major versions of packages (unless the older major versions are particularly popular). For this reason, manually updating outdated packages (as listed by `npm outdated`) ensures passive security updates further into the future.

The majority of packages can be updated to their latest major versions without breaking our build and tests; most of our dependency's major version bumps represent them dropping support for versions of node irrelevant to us.

`grunt-compile-handlebars` is the sole exception, breaking tests and leaving content notably absent on the site. No error is given during the build process, so it is not immediately clear what the breaking change is, however, a review of the package's changelog suggests that the issue would not be difficult to remedy.

#### Conclusion

Grunt's automated tests suggest that the site's functionality would not be impaired by any of the suggested updates. Some brief manual testing of the PR supports this, however, more extensive testing is needed.

## The Other Packages

SEAP PIP has similar features and dependencies to SEAP ESA and SEAP Core, suggesting that what works for one will work for another. It is likely that applying the same procedure to SEAP ESA and SEAP Core will patch a similar number of vulnerabilities.

### CODE REVIEW

**Comment by Hoolean** [comment]
Travis identifies that two peer dependencies are not satisfied, correctly, and fails early. This issue does not rear its ugly head during the build process - functionality is not affected - but it would be proper to correct it anyway:

* `grunt-compile-handlebars` expects an older version of Grunt. This package could be updated, if the breaking change is worked around.
* `grunt-remove` expects an older version of Grunt. This package's latest version is 6 years old and I cannot see where we use it. It can likely be removed.

**Comment by katjam** [comment]
@AlinChindea I guess we should move to `htmlhintplus` here also? If you add that in to this PR I'll be happy for it to go in - while we wait on webpack.

**Comment by AlinChindea** [comment]
> @AlinChindea I guess we should move to `htmlhintplus` here also? If you add that in to this PR I'll be happy for it to go in - while we wait on webpack.

@katjam done! I will update the PR text, too.

**Comment by AlinChindea** [comment]
> Looks good.

@katjam fixed the Travis build failing. I can merge this one, too, if that's ok with you.

**Pull request merged**
